theme: jekyll-theme-minimal
title: Carlos Vinicius
description: Um pouco sobre mim, um pouco sobre meu trabalho
logo: https://raw.githubusercontent.com/paixaoDev/portifa/master/images/IMG_20190911_132153.jpg

show_downloads: true
zip_url: https://www.dropbox.com/s/tz3wgg2pmk0jsyh/Curr%C3%ADculo%20%282%29.pdf?dl=0
tar_url: https://www.dropbox.com/s/gh4ygheglemu0jg/Curr%C3%ADculo.docx?dl=0

google_analytics: UA-158631464-1
