theme: jekyll-theme-minimal
title: Carlos Vinicius
description: Um pouco sobre mim, um pouco sobre meu trabalho

is_project_page: false
is_user_page: true
show_downloads: true

zip_url: https://stackoverflow.com/questions/44637784/github-pages-download-release/44659128
tar_url: https://stackoverflow.com/questions/44637784/github-pages-download-release/44659128
google_analytics: UA-158631464-1
